version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    entrypoint:
        /code/entrypoint.sh
    depends_on:
        - db
