# Generated by Django 2.2.4 on 2019-08-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190809_0749'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
