# Generated by Django 2.2.4 on 2019-08-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190809_0749'),
        ('interview', '0002_auto_20190809_0749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('user_profile', 'start')},
        ),
    ]
